[project]
name = "sae-splade"
version = "0.1.0"
description = "SAE-SPLADE"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "datamaestro>=1.5.2",
    "datamaestro-text>=2025.9.11",
    "experimaestro==2.0.0a8",
    "experimaestro-ir[anserini,neural]",
    "ir-datasets",
    "pandas>=2.3.1",
    "tensorboard>=2.20.0",
    "pyserini==0.21.0",
    "faiss-cpu",
    "torch>=2.7.0",
    "tabulate>=0.9.0",
    "huggingface-hub==0.34.4",
    "transformers==4.37.0",
    "jupyterlab==4.2.5",
    "datasets",
    "pre-commit==4.5.1",
    "matplotlib",
    "seaborn",
    "pandas",
    "umap-learn>=0.5.9.post2",
    "bmp",
]

[tool.uv]
package = true

override-dependencies = [
    "nmslib ; sys_platform == 'never'",
]

[tool.uv.sources]
ir-datasets = { git = "https://github.com/yzong12138/ir_datasets.git" }
datamaestro-text = { git = "https://github.com/experimaestro/datamaestro_text.git", rev="c03e471"}
experimaestro-ir = { git = "https://github.com/experimaestro/experimaestro-ir.git", branch = "sae_splade" }
torch = [
  { index = "pytorch-cu126", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
